demo_avodha_app/urls.py
from django.urls import path
from . import views

app_name='myapp'
urlpatterns = [

    path('',views.demo,name='demo'),
    path('shop/<int:shop_id>',views.detail,name='detail'),
    path('add/',views.add_product,name='add_product'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>', views.delete, name='delete'),

]

demo_avodha_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from demo_avodha_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('demo_avodha_app.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo_avodha_app/models.py
from django.db import models

# Create your models here.
class shop(models.Model):
    name=models.CharField(max_length=100)
    desc=models.TextField()
    price=models.IntegerField()
    img = models.ImageField(upload_to='images/', default='images/default.jpg')

demo_avodha_app/forms.py
from .models import shop
from django import forms
class ModelForm(forms.ModelForm):
    class Meta:
        model=shop
        fields=['name','desc','price','img']

demo_avodha_app/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import shop
from .forms import ModelForm


# Create your views here.

def demo(request, products=None):
    product = shop.objects.all()
    if not products:
        products = []  # If no products, pass an empty list or show a message

    return render(request, "home.html", {'products': product})


# View to display details of a specific product
def detail(request, shop_id):
    try:
        product1 = shop.objects.get(id=shop_id)
    except shop.DoesNotExist:
        return HttpResponse("Product not found", status=404)

    return render(request, 'detail.html', {'product': product1})

#
# def detail(request, shop_id):
#     product1 = shop.objects.get(id=shop_id)
#     return render(request, 'detail.html', {'product': product1})


def add_product(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        price = request.POST.get('price')
        img = request.FILES['img']
        s=shop(name=name,desc=desc,img=img,price=price)
        s.save()
        print("product added")

    return render(request, "add_product.html")


def update(request,id):
    obj=shop.objects.get(id=id)
    form = ModelForm(request.POST or None, request.FILES, instance=obj)
    if(form.is_valid()):
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form, 'obj':obj})

def delete(request,id):
    if request.method == 'POST':
        obj=shop.objects.get(id=id)
        obj.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add_product.html
{% extends 'base.html' %}
{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Product Name"><br>
        <input type="text" name="desc" placeholder="Product Description"><br>
        <input type="text" name="price" placeholder="Product Price"><br>
        <input type="file" name="img" placeholder="Product image"><br>
        <input type="submit" value="ADD">

</form>

{% endblock %}

templates/base.html
{% load static %}

<html lang="en">
<head>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/myapp/style.css' %}">
    <!-- Image and text -->
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
            Online Shopping Center
        </a>
    </nav>


</head>
<body>
{% block body %}
{% endblock %}

</body>
</html>

templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete this item?
    <input type="submit">
</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">

        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img src="{{ product.img.url }}" class="card-img-top" alt="{{ i.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.desc }}
                        {{product.price}}<br>

                        <a class="btn btn-warning" href="{% url 'myapp:update' product.id %}">UPDATE</a>
                        <a class="btn btn-danger" href="{% url 'myapp:delete' product.id %}">DELETE</a>
                </div>
            </div>
        </div>

    </div>
</div>


{% endblock %}

templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="update">

</form>

templates/home.html
{% extends 'base.html' %}
{% block body %}

<!--<a href="/shop/{{i.id}}">{{i.name}}</a>-->
<!--detail given below code means  that path of the code and before detail we given my app that is specified in urls if we have more that one detail name then we get confuse so add that in url and call here so get off confusion-->

<div class="container">
    <div class="row">
        {% for i in products %}
            {% if i.id %}
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ i.img.url }}" class="card-img-top" alt="{{ i.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ i.name }}</h5>
                        <p class="card-text">{{ i.desc }}</p>
                        <a href="{% url 'myapp:detail' i.id %}" class="btn btn-primary">Go Detail</a>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}